experiment: segthor_enet_dice_ce_fg_corrected
seed: 1
device: cuda
notes: ENet + CE (foreground only) + soft Dice (foreground), corrected SEGTHOR labels
data:
  root: data/SEGTHOR_corrected
  preprocess: null
  num_classes: 5
  class_names:
  - background
  - esophagus
  - heart
  - trachea
  - aorta
  label_scale: 63
  patient_regex: (Patient_\d+)_\d{4}
  in_channels: 1
  batch_size: 8
  num_workers: 5
  augment: []
  source_pattern: data/segthor_part1_corrected/train/{patient}/GT.nii.gz
  test_source_pattern: null
model:
  name: enet
  kwargs:
    kernels: 8
    factor: 2
loss:
  name: dice_ce
  kwargs:
    ce_idk:
    - 1
    - 2
    - 3
    - 4
    dice_idk:
    - 1
    - 2
    - 3
    - 4
    ce_weight: 1.0
    dice_weight: 1.0
optim:
  name: adam
  kwargs:
    lr: 0.0005
    betas:
    - 0.9
    - 0.999
scheduler:
  name: none
  kwargs: {}
train:
  epochs: 25
  select_metric: val_dice_fg
  max_failed_batches: 5
  debug_samples: 0
eval:
  classes:
  - 1
  - 2
  - 3
  - 4
wandb:
  mode: disabled
  entity: ''
  project: ai4mi-segthor
  tags: []
  image_every: 5
paths:
  run_root: runs
  metrics_dir: metrics
